apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: expected-vals-scrape
spec:
  schedule: "2/12 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: handicap-scrape-job
            image: gcr.io/albertlockett-test2/sports-betting:latest
            imagePullPolicy: Always
            args:
            - expected-values
            env:
            - name: CFG_ES_URL
              value: http://elasticsearch-master:9200
          restartPolicy: Never