apiVersion: apps/v1
kind: Deployment
metadata:
  name: sources-service
  labels:
    app: sources-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sources-service
  template:
    metadata:
      labels:
        app: sources-service
    spec:
      containers:
      - name: sources-service
        image: gcr.io/albertlockett-test2/sports-betting-service:latest
        imagePullPolicy: Always
        env:
        - name: ENDPOINT
          value: http://sources-service
---
apiVersion: v1
kind: Service
metadata:
  name: sources-service
spec:
  selector:
    app: sources-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080